services:
  cgit:
    image: ghcr.io/dpi0/cgit-docker:9a9a947
    container_name: cgit
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /srv/git:/opt/git
      - ../config/cgit-config:/opt/cgit/cgitrc
      - ../scripts/cgit-30-fix-permissions.sh:/docker-entrypoint.d/30-fix-permissions.sh
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: 0.25
    labels:
      traefik.enable: true
      traefik.http.routers.git.entrypoints: websecure
      traefik.http.routers.git.rule: "Host(`cgit.home.$DOMAIN`)"
      traefik.http.services.git.loadbalancer.server.port: 80
