services:
  beets:
    image: dpi0/beets-docker:minimal-v1.0.0
    container_name: beets
    volumes:
      - $DATA/docker/beets/config:/data/config
      - ../config/beets-config.yaml:/data/config/config.yaml
      - $DATA/docker/beets/db:/data/db
      - $DATA/docker/beets/logs:/data/logs
      - $DATA/downloads/Music:$DATA/downloads/Music
      - $DATA/library/Music:$DATA/library/Music
    user: "1000:1000"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 1.0
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BEETSDIR: /data/config
    labels:
      traefik.enable: false
