services:
  sonarr:
    depends_on:
      - traefik
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - $DATA/docker/sonarr/config:/config
      - /data/library/Television:/data/library/Television
      # - /data/downloads/TV:/data/downloads/TV
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: 0.25
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.rule: "Host(`sonarr.home.$DOMAIN`)"
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
